name: Upload Apk to Firebase Distribution

on:
  push:
    branches: 
    - master
    - develop
    - feature/refactor_compose
  pull_request:
    branches:
    - master
    - develop

jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#
#    - uses: actions/checkout@v4
#
#    - name: set up JDK 17
#      uses: actions/setup-java@v4
#      with:
#        java-version: '17'
#        distribution: 'zulu'
#        cache: gradle
#
#    - name: Grant execute permission for gradlew
#      run: chmod +x gradlew
#    - name: Build with Gradle
#      run: ./gradlew assembleDebug
#
#    - name: Upload to Firebase App Distribution
#      uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
#      with:
#        appId: ${{ secrets.FIREBASE_APP_ID }}
#        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
#        file: app/build/outputs/apk/debug/app-debug.apk
#        groups: android
#        releaseNotesFile: release_note.md

  notify:
#    needs: [build]
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v4

    - name: Get version
      id: version
      run: |
        export versionName="$(./gradlew -q app:printVersionName)"
        echo "version=$versionName" >> $GITHUB_OUTPUT
    
    - name: Get release notes
      id: release_note
      run: |
        export content="$(cat release_note.md)"
        content=${content//'"'/'\"'/}
        content=${content//$'\n'/'\n'}
        echo "release_note=$content" >> $GITHUB_OUTPUT
        
    - name: Post build status to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.25.0
      with:
        channel-id: 'C049MCCJ38B'
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<!channel> GitHub Action build result: ${{ job.status }}\n"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Feature*\n${{ steps.release_note.outputs.release_note }}"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Branch*\n${{ github.ref_name }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Version*\n${{ steps.version.outputs.version }}"
                  }
                ]
              }
            ]
          }      
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
