name: Upload Apk to Firebase Distribution

on:
  push:
    tags:
      - '*-release-alpha'

jobs:
  #  build:
  #
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #
  #    - uses: actions/checkout@v4
  #
  #    - name: set up JDK 17
  #      uses: actions/setup-java@v4
  #      with:
  #        java-version: '17'
  #        distribution: 'zulu'
  #        cache: gradle
  #
  #    - name: Grant execute permission for gradlew
  #      run: chmod +x gradlew
  #    - name: Build with Gradle
  #      run: ./gradlew assembleProductionRelease
  #
  #    - name: Upload to Firebase App Distribution
  #      uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
  #      with:
  #        appId: ${{ secrets.FIREBASE_APP_ID }}
  #        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
  #        file: app/build/outputs/apk/production/release/app-production-release.apk
  #        groups: android
  #        releaseNotesFile: release_notes.md

  build:

    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}
      release_notes: ${{ steps.release_notes.outputs.release_notes }}
      branch: ${{ steps.check_step.outputs.branch }}

    steps:

      - name: Check out source code.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current branch
        id: check_step
        # 1. Get the list of branches ref where this tag exists
        # 2. Remove 'origin/' from that result
        # 3. Put that string in output
        # => We can now use function 'contains(list, item)''
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch="$(echo ${raw//origin\//} ${raw//\(/'\('} ${raw//\)/'\)'} | tr -d '\n')"
          echo "{name}=branch" >> $GITHUB_OUTPUT
          echo "Branches where this tag exists : $branch."

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Prepare Keystore file
        run: |
          echo "${{ secrets.ENCRYPTED_KEY_STORE }}" > keystore.asc
          gpg -d --passphrase "${{ secrets.KEY_STORE_PASSPHRASE }}" --batch keystore.asc > keystore.jks

      - name: Prepare SigningConfig variables
        run: |
          echo "STORE_FILE_NAME=keystore.jks" &>> signing.properties
          echo "STORE_PASSWORD=${{ secrets.KEY_PASSWORD }}" &>> signing.properties
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" &>> signing.properties
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" &>> signing.properties

      - name: Get version
        id: version
        run: |
          export versionName="$(./gradlew -q app:printVersionName)"
          echo "version=$versionName" >> $GITHUB_OUTPUT

      - name: Get release notes
        id: release_notes
        run: |
          export content="$(cat release_notes.md)"
          content=${content//'"'/'\"'/}
          content=${content//$'\n'/'\n'}
          echo "release_notes=$content" >> $GITHUB_OUTPUT

      - name: Build DevRelease APK with Gradle
        id: build
        run: |
          ./gradlew app:assembleDevRelease

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_DEV }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT_DEV }}
          file: app/build/outputs/apk/dev/release/app-dev-release.apk
          groups: android
          releaseNotesFile: release_notes.md

  notify_success:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Notify Success
        id: notify_success
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'C049MCCJ38B'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<!channel> :white_check_mark: Upload app to FirebaseDistribution: Success\n"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Release Notes*\n${{ needs.build.outputs.release_notes }}"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Tag*\n${{ github.ref_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Version*\n${{ needs.build.outputs.version }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  notify_failure:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Notify Failure
        id: notify_failure
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'C049MCCJ38B'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<!channel> :x: Upload app to FirebaseDistribution: Failed!\n"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*You can check error from here*\n"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":github: Failed action!"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Tag*\n${{ github.ref_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Version*\n${{ needs.build.outputs.version }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}