name: Deploy app to Google Play Internal Store

on:
  push:
    branches:
      - 'master'
    tags:
      - '*-release-production'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Prepare Keystore
        run: |
          echo "${{ secrets.ENCRYPTED_KEY_STORE }}" > keystore.asc
          gpg -d --passphrase "${{ secrets.KEY_STORE_PASSPHRASE }}" --batch keystore.asc > keystore.jks

      - name: Prepare Keystore variables
        run: |
          echo "STORE_FILE_NAME=keystore.jks" &>> signing.properties
          echo "STORE_PASSWORD=${{ secrets.KEY_PASSWORD }}" &>> signing.properties
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" &>> signing.properties
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" &>> signing.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew bundleProductionRelease

      - name: Get version
        id: version
        run: |
          export versionName="$(./gradlew -q app:printVersionName)"
          echo "version=$versionName" >> $GITHUB_OUTPUT

      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          releaseFiles: app/build/outputs/bundle/productionRelease/app-production-release.aab
          serviceAccountJsonPlainText: ${{ secrets.PUBLISH_SERVICE_ACCOUNT_JSON }}
          packageName: com.kondee.wakeat
          track: internal
          status: draft

#          userFraction: 0.33
#          status: completed
#          whatsNewDirectory: deploy/whatsnew

  notify_success:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Notify Success
        id: notify_success
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'C049MCCJ38B'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<!channel> :white_check_mark: Deploy Application to Google Play Internal Store: Success\n"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Release Notes*\n${{ needs.build.outputs.release_notes }}"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Tag*\n${{ github.ref_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Version*\n${{ needs.build.outputs.version }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  notify_failure:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Test Exception
        run: |
          echo "${{ needs.build.outputs.exception }}"

      - name: Notify Failure
        id: notify_failure
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'C049MCCJ38B'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<!channel> :x: Deploy Application to Google Play Internal Store: Failed!\n"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Exception*\n${{ needs.build.outputs.exception }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":github: Failed action!"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Tag*\n${{ github.ref_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Version*\n${{ needs.build.outputs.version }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}